<a href="https://colab.research.google.com/github/Valeriaya512/R/blob/main/%E9%97%9C%E8%81%AF%E8%B3%87%E6%96%99%E5%BA%AB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Primary Key
用來唯一識別資料表中每一筆資料的欄位，通常不能重複，也不能是空值
*  每一筆資料都要能被唯一找到
*  不能重複，也不能是NULL
*  一張表通常會有一個主鍵，可能是單一欄位，也可能是複合欄位

## Foreign Key
用來連結兩個資料表的欄位，它的值通常會對應到另一張表的主鍵，目的是維持資料一致性與參照完整性
*  用來表示表與表之間的關係
*  要能對應到另一張表的主鍵，否則可能會違反資料完整性
*  可以幫助避免插入不存在的參照資料

In [3]:
library(tidyverse)

students <- tibble(
  student_id = c(1, 2, 3),   #Primary Key
  student_name = c("Amy", "Ben", "Cathy")
)

orders <- tibble(
  order_id = c(101, 102, 103, 104),
  student_id = c(1, 1, 2, 3),  #Foreign Key
  course = c("R", "SQL", "Python", "Statistics")
)

students
orders

  student_id student_name
1 1          Amy
2 2          Ben
3 3          Cathy

  order_id student_id course
1 101      1          R
2 102      1          SQL
3 103      2          Python
4 104      3          Statistics